const root=document.querySelector('#app');
const state={bundle:null,search:[],selected:null,tab:'researcher',view:'family',surface:'atlas',filters:new Set(),zoom:1,request:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=v=>/^https:\/\//.test(v??'')?esc(v):'#';
const pct=v=>v==null?'Unknown':`${Math.round(v*100)}%`;
const get=async path=>{const r=await fetch(path);if(!r.ok)throw Error('Evidence could not be loaded. Please retry.');return r.json();};
const sourceLink=s=>`<a href="${url(s.source_url)}" target="_blank" rel="noopener noreferrer">${esc(s.identifier||s.source)} ↗</a>`;
const sourceRows=rows=>rows.map(s=>`<article class="source"><div>${sourceLink(s)}</div><h4 class="source-title">${esc(s.title||s.source)}</h4><p>${esc(s.extracted_claim||s.summary)}</p><div class="source-facts"><span>${esc(s.source_family||'Source')}</span><span>${esc(s.evidence_type.replaceAll('_',' '))}</span><span>${esc(s.claim_kind?.replaceAll('_',' ')||'Source report')}</span></div><p class="source-design"><b>Study / record:</b> ${esc(s.study_design||'Design not extracted')}</p>${s.pmid?`<p><b>Sample / denominator:</b> ${esc(s.sample_size?.reported||s.sample_size?.location||'Not extracted')} <small>${esc(s.sample_size?.reported?'('+s.sample_size.location+')':'')}</small></p><p class="source-bibliography">${esc(s.journal||'Journal unavailable')} · ${esc(s.publication_year||'Year unavailable')}<br>PMID ${esc(s.pmid)}${s.doi?` · <a href="${url('https://doi.org/'+s.doi)}" target="_blank" rel="noopener noreferrer">DOI ↗</a>`:' · DOI unavailable'}${s.pmc_url?` · <a href="${url(s.pmc_url)}" target="_blank" rel="noopener noreferrer">PMC ↗</a>`:''}</p><details class="source-details"><summary>Authors & indexed publication types ⌄</summary><p>${esc(s.authors?.join('; ')||'Authors unavailable')}</p><p>${esc(s.publication_types?.join('; ')||'Publication type unavailable')}</p>${s.corrections?.length?`<p>Linked notices: ${esc(s.corrections.map(c=>c.type+(c.pmid?' · PMID:'+c.pmid:'')).join('; '))}</p>`:''}</details>`:''}${s.review_status?`<p><b>Condition classification:</b> ${esc(s.condition_classification)} · ${esc(s.condition_record)}<br><b>Review:</b> ${esc(s.review_status)}; evaluated ${esc(s.classification_evaluated_at)}<br><b>Broader variant aggregate:</b> ${esc(s.variant_aggregate_classification)}</p>`:''}${s.principal_investigators?`<p><b>Investigators:</b> ${esc(s.principal_investigators.join('; '))}<br>${esc(s.organization)}<br>Project period ${esc(s.project_start_date)} → ${esc(s.project_end_date)}</p>`:''}<p class="source-uncertainty"><b>Uncertainty:</b> ${esc(s.uncertainty||'Not independently reviewed')}</p><small>${esc(s.publication_date||'Publication date not available')} · checked ${esc(s.retrieved_at)}</small></article>`).join('');
const metric=(label,value,key)=>`<button class="metric" data-metric="${key}" aria-label="Explain ${esc(label)}"><span>${esc(label)} <i>↗</i></span><strong>${esc(value)}</strong></button>`;

function shell(){
 root.innerHTML=`<header class="header"><a class="brand" href="#"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M10 29 20 10 31 27M10 29l21-2"/><circle cx="10" cy="29" r="4"/><circle cx="20" cy="10" r="4"/><circle cx="31" cy="27" r="4"/></svg><span>MEDR5 <b>Atlas</b></span></a><span class="edition">BUFFALO INITIATIVE CHALLENGE · HACKATHON EDITION</span><a class="demo-link" href="/demo">Cached demo ↗</a><span class="local-status"><i></i> Cached evidence ready</span></header>
 <main><div class="intro"><div><p class="eyebrow">CONNECTED EVIDENCE FOR RARE-DISEASE COMMUNITIES</p><h1>Find the connection.<br>Define the next step.</h1><p class="lede">Understand why a connection matters, find reusable research, and identify what to investigate next.</p></div><div class="searchbox"><label for="disease-search">Find a disease or causal gene</label><div class="search-field"><span aria-hidden="true">⌕</span><input id="disease-search" placeholder="Try Angelman, UBE3A or a rare disease" autocomplete="off" role="combobox" aria-expanded="false" aria-controls="search-results"><button id="search-button" aria-label="Search diseases">Search</button></div><div id="search-results" role="listbox" hidden></div><small>4 curated pilots · broader catalog discovery with evidence gates</small></div></div>
 <div class="scope"><span>Pilot validated: monogenic neurology</span><span>Platform architecture: monogenic rare diseases</span><small>Prototype checks, not clinical validation</small></div>
 <div class="pilot-tabs" aria-label="Curated pilot diseases">${[['angelman','Angelman / UBE3A'],['cdkl5','CDKL5 deficiency'],['cacna1a','CACNA1A disorders'],['stxbp1','STXBP1 disorder']].map(([id,label])=>`<button data-disease="${id}">${label}</button>`).join('')}</div>
 <div id="content" aria-live="polite"></div>
 <footer>Research decision support — not medical advice. Therapeutic hypotheses require experimental and clinical validation.<span>From fragmented evidence to the next testable action.</span></footer></main>
 <dialog id="detail-dialog"><div class="dialog-head"><h2 id="detail-title">Evidence</h2><button id="close-detail" aria-label="Close details">✕</button></div><div id="detail-body"></div></dialog>`;
 document.querySelector('#close-detail').onclick=()=>document.querySelector('#detail-dialog').close();
 document.querySelector('#detail-dialog').addEventListener('click',e=>{if(e.target.id==='detail-dialog')e.target.close();});
 const input=document.querySelector('#disease-search');let debounce;
 input.addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(()=>searchDiseases(input.value),200);});
 input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchDiseases(input.value);}if(e.key==='Escape')closeSearch();});
 document.querySelector('#search-button').onclick=()=>searchDiseases(input.value);
 document.addEventListener('click',e=>{if(!e.target.closest('.searchbox'))closeSearch();});
 document.querySelector('.pilot-tabs').onclick=e=>{const b=e.target.closest('[data-disease]');if(b)loadDisease(b.dataset.disease);};
}
function closeSearch(){document.querySelector('#search-results').hidden=true;document.querySelector('#disease-search').setAttribute('aria-expanded','false');}
async function searchDiseases(q){
 const token=++state.request;const box=document.querySelector('#search-results');
 try{const data=await get('/api/search?q='+encodeURIComponent(q));if(token!==state.request)return;
 state.search=data.results;box.hidden=false;document.querySelector('#disease-search').setAttribute('aria-expanded','true');
 box.innerHTML=data.results.length?data.results.map((r,i)=>`<button role="option" data-result="${i}" aria-selected="false"><strong>${esc(r.name)}</strong><small>${esc(r.curated?r.gene+' · curated pilot':r.evidence_depth)}</small></button>`).join('')+`<p>${data.total} matches · showing ${data.results.length}. Refine the search for more.</p>`:'<p>No curated or catalog match. A disease/gene needs cited mechanism and candidate evidence before ranking.</p>';
 box.onclick=e=>{const b=e.target.closest('[data-result]');if(!b)return;const r=state.search[Number(b.dataset.result)];closeSearch();if(r.curated)loadDisease(r.id);else loadDiscovery(r.id);};
 }catch(e){box.hidden=false;box.innerHTML=`<p>${esc(e.message)}</p>`;}
}
async function loadDiscovery(id){
 state.loadToken=(state.loadToken||0)+1;const token=state.loadToken;
 const d=await get('/api/discovery?id='+encodeURIComponent(id));if(token!==state.loadToken)return;
 document.querySelectorAll('[data-disease]').forEach(b=>b.classList.remove('active'));
 document.querySelector('#content').innerHTML=`<section class="card discovery"><span class="badge amber">DISCOVERY ONLY</span><h2>${esc(d.name)}</h2><p>${esc(d.reason)}</p><p>${esc(d.next_step)}</p><a class="button-link" href="${url(d.source_url)}" target="_blank" rel="noopener noreferrer">Open authoritative disease resource ↗</a><p class="muted">The inherited catalog includes non-monogenic conditions. No diagnosis, therapeutic graph or ranking is inferred from a catalog name.</p><button data-return>Return to Angelman demo</button></section>`;
 document.querySelector('[data-return]').onclick=()=>loadDisease('angelman');
}
async function loadDisease(id){
 state.loadToken=(state.loadToken||0)+1;const token=state.loadToken;
 document.querySelector('#content').innerHTML='<div class="card loading">Loading cited biology and hypotheses…</div>';
 try{const bundle=await get('/api/diseases/'+id);if(token!==state.loadToken)return;state.bundle=bundle;state.selected=null;state.filters=new Set(state.bundle.graph.nodes.map(n=>n.type));state.zoom=1;render();}
 catch(e){document.querySelector('#content').innerHTML=`<section class="card"><h2>Evidence unavailable</h2><p>${esc(e.message)}</p><button data-retry>Retry</button></section>`;document.querySelector('[data-retry]').onclick=()=>loadDisease(id);}
}
function render(){
 const b=state.bundle,d=b.disease,p=b.ranking.ranked[0];
 document.querySelectorAll('[data-disease]').forEach(btn=>btn.classList.toggle('active',btn.dataset.disease===d.id));
 document.querySelector('#content').innerHTML=`
 <section class="overview card" id="biology"><div><p class="eyebrow">YOUR DISEASE · A STARTING POINT FOR SHARED RESEARCH</p><h2>${esc(d.name)}</h2><p>${esc(state.view==='family'&&b.hero_journey?b.hero_journey.family_explanation:d.mechanism)}</p><div class="phenotypes">${d.phenotypes.map(s=>`<span>${esc(s)}</span>`).join('')}</div></div><div class="overview-meta"><div><span>Causal gene</span><button data-biology><strong>${esc(d.gene)}</strong> ↗</button></div><div><span>Evidence depth</span><b>${esc(d.evidence_depth)}</b></div><div><span>Inheritance / mechanism</span><b>${esc(d.inheritance)}</b></div><small>Evidence snapshot ${b.snapshot_date} · source-specific confidence</small></div></section>
 <nav class="view-tabs" role="tablist" aria-label="MEDR5 product surfaces">${[['atlas','1 · Atlas'],['connections','2 · Connections / shared assets'],['therapeutic','3 · Therapeutic hypotheses'],['action','4 · Next action']].map(([id,label])=>`<button role="tab" data-surface="${id}" aria-selected="${state.surface===id}">${label}</button>`).join('')}</nav>
 <div id="journey-view" ${state.surface!=='connections'?'hidden':''}><div class="audience-tabs connection-audience" role="tablist" aria-label="Connection audience">${[['family','Family / Patient Group'],['researcher','Researcher']].map(([id,label])=>`<button role="tab" data-view="${id}" aria-selected="${state.view===id}">${label}</button>`).join('')}</div>${journeyView(b)}</div>
 <div id="next-action-view" ${state.surface!=='action'?'hidden':''}>${actionView(b)}</div>
 <div id="therapeutic-view" ${state.surface!=='therapeutic'?'hidden':''}>
 <nav class="flow-nav" aria-label="Matching workflow"><a href="#matching">02 Match medicines ↓</a><a href="#tradeoffs">03 Review trade-offs ↓</a><a href="#experiment">04 Next experiment ↓</a><a href="#evidence">Evidence & graph ↓</a></nav>
 <div class="workspace"><div class="main-column">
 <section id="matching"><div class="section-heading"><div><p class="eyebrow">02 · THERAPEUTIC MATCHING</p><h2>Repurposing hypotheses</h2></div><span class="badge">DETERMINISTIC MEDR5 CORE</span></div>
 <div class="mechanism-chain"><div><small>Disease direction</small><strong>${esc(d.gene)} ${d.direction==='loss_of_function'?'↓':d.direction==='variant_dependent'?'↕':'↑'}</strong></div><span>→</span><div><small>Desired perturbation</small><strong>${d.direction==='loss_of_function'?'Restore activity ↑':'Resolve variant direction'}</strong></div><span>→</span><div><small>Evidence gate</small><strong>${p?'Sourced experimental effect':'Ranking withheld'}</strong></div></div>
 ${p?`<article class="candidate card"><div class="candidate-title"><div><span class="badge teal">#1 · REPURPOSING RESEARCH HYPOTHESIS</span><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p></div><button class="priority" data-metric="priority"><small>Mechanistic priority</small><strong>${p.priority_score.toFixed(2)}</strong><span>Heuristic, not efficacy ↗</span></button></div><div class="metrics">${metric('Curated-axis coverage',pct(p.coverage),'coverage')}${metric('Direction match',p.direction_alignment===1?'Aligned ↑':p.direction_alignment,'direction')}${metric('Sourced spillover',p.spillover.known_count+' mechanism(s)','spillover')}${metric('Effect evidence','Human cells + animal','evidence')}</div><p class="axis-note">${p.covered_targets.length} of ${d.signature.length} curated molecular axis(es) covered. This is not ${pct(p.coverage)} of the disease, symptom rescue, or safety.</p><button class="text-button" data-show-sources>Inspect supporting evidence ↗</button></article>`:
 `<div class="card empty-state"><span class="badge amber">EVIDENCE GATE</span><h3>Do not rank what is unresolved.</h3><p>${esc(b.ranking.reason)}</p><p>${esc(d.unresolved[0])}</p><button data-biology>Inspect causal evidence ↗</button></div>`}
 ${b.ranking.withheld.map(r=>`<div class="card"><h3>${esc(r.name)} · ranking withheld</h3><p>${esc(r.gate_reason)}</p></div>`).join('')}
 </section>
 ${priorPanel(b)}
 <section id="tradeoffs"><div class="section-heading"><div><p class="eyebrow">03 · WHAT FITS, WHAT REMAINS</p><h2>Mechanistic fit ≠ clinical safety</h2></div></div>
 <div class="tradeoff-grid"><article class="card"><div class="mini-heading"><span class="number">A</span><h3>Remaining biology</h3></div><p class="muted">${p?esc(p.remaining.explanation):'No causal restoration claim is available for this curated pilot.'}</p><ul>${(p?p.remaining.unresolved:d.unresolved).map(s=>`<li>${esc(s)}</li>`).join('')}</ul><div class="note">Uncovered curated targets: ${p?(p.remaining.uncovered_targets.length?p.remaining.uncovered_targets.join(', '):'none in the narrow signature'):'not assessed'}. Unmodelled biology remains.</div></article>
 <article class="card safety"><div class="mini-heading"><span class="number">B</span><h3>Clinical safety evidence</h3></div><span class="badge amber">QUANTITATIVE BURDEN: UNKNOWN</span><p>No safety claim follows from a mechanistic score or a combination score.</p>${p&&p.risk_burden.warnings.length?`<ul>${p.risk_burden.warnings.map(w=>`<li><b>${esc(w.domain)}:</b> ${esc(w.label)}</li>`).join('')}</ul><button class="text-button" data-metric="risk">Inspect sourced risk review ↗</button>`:'<p class="muted">Unknown / insufficient evidence. No numeric organ-burden score is assigned.</p>'}</article></div>
 <article class="card complementary"><h3>Complementary medicine / bundle</h3><p>${esc(b.complementary.explanation)}</p>${b.complementary.candidates.length?b.complementary.candidates.map(c=>`<p>${esc(c.name)} · net mechanistic gain ${c.net_gain}. Unvalidated research hypothesis; safety unknown.</p>`).join(''):'<div class="note">No supported add-on clears the evidence and non-redundancy gate. Combining UBE3A-restoring perturbations is not automatically complementary.</div>'}</article>
 </section>
 <section class="card comparison"><p class="eyebrow">COMPARE INTERVENTIONS · NOT THERAPEUTIC EQUIVALENCE</p><h3>Same desired effect, different trade-offs</h3><div class="table-scroll"><table><thead><tr><th>Intervention / role</th><th>Curated-axis coverage</th><th>Direction</th><th>Sourced spillover</th><th>Effect evidence</th><th>Clinical safety</th></tr></thead><tbody>${b.comparison.map(c=>`<tr><td><strong>${esc(c.name)}</strong><small>${esc(c.role.replaceAll('_',' '))}</small></td><td>${pct(c.coverage)}</td><td>${c.direction_alignment===1?'Aligned ↑':esc(c.direction_alignment??'Unknown')}</td><td>${c.spillover.known_count} listed; inventory incomplete${c.spillover.unknown?'; other effects unknown':''}</td><td>${esc(c.evidence.level)}</td><td>Quantitative burden unknown</td></tr>`).join('')}</tbody></table></div><p class="muted">A source-reported restoration effect is not predicted treatment efficacy. Antisense and research compounds are comparators, not approved repurposed medicines.</p></section>
 <section id="mimicry"><div class="section-heading"><div><p class="eyebrow">OPTIONAL · ISOLATE THE MECHANISM</p><h2>Mechanistic surrogates</h2></div></div><div class="surrogate-grid">${b.surrogates.length?b.surrogates.map((s,i)=>`<article class="card"><span class="badge">RESEARCH COMPARATOR</span><h3>${esc(s.name)}</h3><p>${esc(s.summary)}</p><dl><dt>Observed overlap</dt><dd>${esc(s.overlap.join(', '))} restoration</dd><dt>Different observed profile</dt><dd>${esc(s.divergence.join(', ')||'Mechanistic divergence unresolved')}; other effects unknown</dd></dl><button class="text-button" data-surrogate="${i}">Compare evidence ↗</button></article>`).join(''):`<article class="card empty-state"><p>No sourced, direction-matched surrogate in this pilot. No substitute is inferred.</p></article>`}</div><details class="card optional"><summary>Optional physiology research layer</summary><p>${esc(b.physiology.reason)}</p><p>Physiology perturbations are experimental probes, not lifestyle substitutes for disease-modifying therapy.</p></details></section>
 <section id="experiment" class="card experiment"><p class="eyebrow">04 · NEXT TESTABLE ACTION</p><div class="experiment-head"><h2>${esc(b.experiment.title)}</h2><span class="badge">PROPOSED EXPERIMENT</span></div><p class="question">${esc(b.experiment.question)}</p><p class="muted">${esc(b.experiment.model)}</p><div class="experiment-grid"><div><h4>Comparison arms</h4><ol>${b.experiment.arms.length?b.experiment.arms.map(a=>`<li>${esc(a)}</li>`).join(''):'<li>Obtain functional direction and candidate evidence first.</li>'}</ol></div><div><h4>Predefine readouts</h4><ul>${b.experiment.readouts.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div></div><div class="kill"><b>Early-kill / falsification</b><p>${esc(b.experiment.early_kill)}</p><p>${esc(b.experiment.falsifier)}</p></div><button class="text-button" data-experiment-sources>View evidence behind the question ↗</button></section>
 </div><aside class="actions card"><p class="eyebrow">ACTIONABLE NEXT STEPS</p><h2>From evidence to action</h2><div class="audience-tabs" role="tablist"><button role="tab" data-audience="researcher" aria-selected="${state.tab==='researcher'}">Researcher</button><button role="tab" data-audience="patient" aria-selected="${state.tab==='patient'}">Patient / Family</button></div><div id="action-list" role="tabpanel"></div><button id="export-brief" class="outline-button">Download cited evidence brief ↓</button><p class="muted small">Safe navigation, no individual treatment or trial-eligibility recommendation.</p><div class="snapshot">Offline demo evidence<br><strong>${b.snapshot_date}</strong><br>Trial status is a dated registry snapshot.</div></aside></div>
 </div>
 <section id="evidence" class="evidence-section"><details class="card" id="graph-details" ${state.surface==='atlas'?'open':''}><summary><div><p class="eyebrow">EVIDENCE / PROVENANCE SUBSTRATE</p><h2>Inspect the knowledge graph</h2><p>Trace mechanistic neighbors, model reuse and therapeutic hypotheses to their sources.</p></div><span>${b.graph.nodes.length} nodes · ${b.graph.edges.length} cited edges ⌄</span></summary><div class="legend"><span>FACT</span><span>INFERENCE</span><span>HYPOTHESIS</span><span>CLINICAL EVIDENCE</span><span>UNKNOWN</span></div><div id="graph-controls" class="graph-controls"></div><div class="graph-layout"><div><div class="graph-tools"><span>Click a node or an edge to inspect its source.</span><button id="zoom-out" aria-label="Zoom out graph">−</button><button id="zoom-in" aria-label="Zoom in graph">+</button><button id="zoom-reset">Reset</button></div><div id="graph-view"></div></div><div id="graph-inspector" class="inspector"><h3>Inspect a relationship</h3><p>Select a node or an edge. Every evidence-bearing item carries provenance and a contextual evidence level.</p></div></div></details>
 <details class="card sources-panel"><summary><h3>Studies, sources & evidence quality</h3><span>${b.studies.length} study sources ⌄</span></summary><p class="source-policy"><strong>Evidence quality is separate from mechanistic fit.</strong> Inspect study design, sample context and uncertainty below. Journal names are bibliographic metadata; prestige does not increase a score. Literature comes through PubMed / PMC without a journal allowlist. No Ovid dependency.</p>${sourceRows(b.studies)}<details><summary>Ontology, variant, programme & community records ⌄</summary><p class="source-policy">MONDO / HPO provide terminology; ClinVar provides reviewed variant assertions; ClinicalTrials.gov and NIH RePORTER provide dated records. OMIM / Orphanet identifiers are cross-reference verified; direct licensed or blocked contents were not ingested. Directory presence does not imply a partnership or registry access.</p>${sourceRows(b.sources.filter(s=>!b.studies.some(p=>p.id===s.id)))}</details></details>
 <details class="card ai-panel"><summary><div><p class="eyebrow">OPENAI + DETERMINISTIC MEDR5</p><h3>Evidence extraction workbench</h3></div><span>Drafts, never automatic facts ⌄</span></summary><p>OpenAI Codex assisted the cited entity/relationship curation and family explanation during development. The runtime OpenAI Responses adapter extracts source-bound relationships with a strict schema. MEDR5 code alone computes scores. Saved draft replay is offline and is not a live API call.</p><div class="ai-controls"><button id="replay-ai" ${d.id!=='angelman'?'disabled':''}>Replay saved AI-assisted extraction</button><button id="openai-ai" class="outline-button" ${d.id!=='angelman'?'disabled':''}>Extract with OpenAI</button><button id="live-ai" class="outline-button" ${d.id!=='angelman'?'disabled':''}>Local LLM alternative</button></div><p class="muted">No automatic graph promotion. Source-span checks do not prove scientific meaning. OpenAI runtime requires a server-side OPENAI_API_KEY; no key is placed in the browser.</p><div id="ai-result" aria-live="polite"></div></details></section>`;
 const evidence=document.querySelector('#evidence');evidence.hidden=state.surface!=='atlas';document.querySelector('.view-tabs').insertAdjacentElement('afterend',evidence);
 bind();renderActions();renderGraph();
}
function actionView(b){
 const e=b.experiment,h=b.hero_journey;
 return `<section class="card closing"><p class="eyebrow">NEXT ACTION · RESEARCH HYPOTHESIS</p><h2>${esc(h?h.collaboration.title:e.title)}</h2><p>${esc(h?h.collaboration.action:e.question)}</p><div class="action-split"><div><h3>Patient-group next step</h3><p>${esc(h?h.collaboration.limitation:'Use the official group and cited disease resource to discuss the evidence gap.')}</p>${b.next_steps.patient.map(a=>`<p><a href="${url(a.url)}" target="_blank" rel="noopener noreferrer">${esc(a.title)} ↗</a><br><small>${esc(a.text)}</small></p>`).join('')}${h?'<button data-collaboration>Review shared research brief ↓</button>':''}</div><div><h3>Researcher: next falsification experiment</h3><p>${esc(e.question)}</p><p class="muted">${esc(e.model)}</p><div class="kill"><b>What would make us abandon it?</b><p>${esc(e.early_kill)}</p><p>${esc(e.falsifier)}</p></div><button data-action-evidence>Inspect experiment evidence ↗</button></div></div><div class="architecture-mini" aria-label="OpenAI and MEDR5 architecture"><span><b>OpenAI</b><small>Source-bound extraction / explanation</small></span><i>→</i><span><b>Typed graph</b><small>Evidence / provenance</small></span><i>→</i><span><b>MEDR5</b><small>Deterministic direction-aware reasoning</small></span></div><p class="muted small">OpenAI Codex assisted curation and explanations. Runtime OpenAI extraction requires a server-side key. Saved replay is not a live API call. Mechanistic fit does not establish clinical safety. Model access, collaborators and 10x acceleration remain unvalidated.</p><blockquote class="pitch-line">An atlas tells a rare-disease community what is known. MEDR5 Atlas connects the communities and evidence, then reasons over the biology to show what should be investigated next.</blockquote><button data-closing-atlas>Return to Atlas ↗</button></section>${h?accelerationView(h):''}`;
}
function accelerationView(h){return `<section class="card acceleration"><p class="eyebrow">10X ACCELERATION · UNMEASURED HYPOTHESIS</p><h3>Decision on which therapeutic hypothesis deserves experimental validation</h3><div class="acceleration-grid"><div><h4>Current route</h4><ol>${h.acceleration.current.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><div><h4>MEDR5 Atlas route</h4><ol>${h.acceleration.atlas.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div></div><p>${esc(h.acceleration.assumption)}</p><details><summary>Assumptions & measurement plan ⌄</summary><p>${esc(h.acceleration.measurement_plan)}</p></details></section>`;}
function journeyView(b){
 const h=b.hero_journey;
 if(!h)return `<section class="card"><p class="eyebrow">EVIDENCE DEPTH: CURATED NAVIGATION</p><h2>A community and evidence starting point</h2><p>This pilot has cited disease biology, published studies and an official patient organization. No cross-disease mechanism path is curated here yet; phenotype similarity alone does not justify grouping or drug transfer.</p>${b.next_steps.patient.map(a=>`<article class="source"><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p><a href="${url(a.url)}" target="_blank" rel="noopener noreferrer">Open verified resource ↗</a></article>`).join('')}<button data-next-view="therapeutic">Review evidence-gated therapeutic opportunities →</button><p class="muted">For the complete cross-community demo, choose Angelman / UBE3A.</p></section>`;
 const group=b.graph.nodes.find(n=>n.id===h.neighbor.organization).provenance[0];
 const own=b.graph.nodes.find(n=>n.id===b.disease.organization).provenance[0];
 const research=state.view==='researcher';
 return `<section class="journey-intro"><p class="eyebrow">${research?'WHY THIS CONNECTION MATTERS':'WHO IS CONNECTED TO US?'}</p><h2>${research?'A shared assay context, not a shared treatment':'A related community. A reusable starting point.'}</h2><p class="muted">${research?esc(h.cluster_name):'The connection is how genes are switched on by parent of origin. The diseases need different therapeutic directions.'}</p></section>
 <section class="cluster-path card" aria-label="Defensible mechanistic cluster"><div class="path-card"><span class="badge">YOUR COMMUNITY</span><h3>Angelman syndrome</h3><p>Maternal UBE3A activity ↓</p><small>Restoration is the desired research direction.</small></div><div class="path-arrow" aria-hidden="true">↔</div><button class="path-card central" data-hero-sources="cluster"><span class="badge teal">SOURCED CONNECTION</span><h3>Genomic imprinting</h3><p>Published paired cell-model work</p><small>Why these diseases connect ↗</small></button><div class="path-arrow" aria-hidden="true">↔</div><div class="path-card"><span class="badge">RESEARCH-ASSET NEIGHBOR</span><h3>Prader-Willi syndrome</h3><p>Paternal gene expression ↓</p><small>Different targets; no drug transfer inferred.</small></div></section>
 <div class="journey-cards"><article class="card"><p class="eyebrow">01 · FIND THE OTHER COMMUNITY</p><h3>${esc(group.source)}</h3><p>${research?esc(h.neighbor.mechanism):'A related patient community studying the same chromosome region with a different parent-of-origin problem.'}</p><a href="${url(group.source_url)}" target="_blank" rel="noopener noreferrer">Explore the related organization ↗</a><div class="community-pair"><a href="${url(own.source_url)}" target="_blank" rel="noopener noreferrer">Angelman community ↗</a></div><p class="muted small">${esc(h.neighbor.caveat)}</p></article>
 <article class="card"><p class="eyebrow">02 · FIND REUSABLE WORK</p><h3>Paired disease cell-model methodology</h3><p>${esc(h.asset.why_reusable)}</p><button class="text-button" data-hero-sources="asset">Inspect published model / study ↗</button><p class="muted small">${esc(h.asset.availability)}</p>${research?`<p class="muted small">Publication team: ${esc(h.asset.researcher)}</p>${b.research_programmes.map((p,i)=>`<div class="community-pair"><h4>NIH-funded research programme</h4><p>${esc(p.project_title)}</p><p class="small">${esc(p.principal_investigators.join('; '))} · ${esc(p.organization)}</p><button class="text-button" data-programme-source="${i}">Inspect NIH RePORTER record ↗</button><p class="small">${esc(p.availability)}</p></div>`).join('')}`:''}</article></div>
 <details class="card optional"><summary>Broader community / patient information resources ⌄</summary><div class="resource-links">${b.patient_resources.map(sourceLink).join('')}</div><p>Official navigation resources; no partnership, specific registry availability or treatment benefit is inferred.</p></details>
 <section class="card counterexample"><div><span class="badge amber">COUNTEREXAMPLE · DO NOT TRANSFER THE DIRECTION</span><h3>Same gene, opposite dosage context</h3><p>${esc(h.counterexample.explanation)}</p><p class="muted small">${esc(h.counterexample.distinction)}</p></div><button data-hero-sources="counter">Inspect non-connection ↗</button></section>
 ${research?`<section class="card research-context"><p class="eyebrow">EVIDENCE INTEGRITY</p><h3>Observed model connection → inferred reuse → proposed experiment</h3><div class="legend"><span>FACT: published paired models</span><span>INFERENCE: methods may be reusable</span><span>HYPOTHESIS: shared validation experiment</span></div><p>UBE3A loss and paternal-region loss are different causal problems. The mechanistic cluster shares imprinting biology and experimental methods, not clinical treatment response. UBE3A dosage gain is excluded from the restoration cluster.</p><details><summary>Context-dependent evidence and gaps ⌄</summary><p>Meng et al. reported incomplete phenotype rescue despite restored expression. Cellular observations are not human clinical efficacy. Neighboring imprinted transcripts, developmental timing, exposure and cell-model access still need validation.</p></details><button class="text-button" data-hero-sources="collaboration">Inspect evidence and limitations ↗</button></section>`:''}
 <section class="card shared-action"><p class="eyebrow">03 · A CONCRETE SHARED NEXT STEP</p><h2>${esc(h.collaboration.title)}</h2><p>${esc(h.collaboration.action)}</p><details><summary>What the research brief should contain ⌄</summary><ul>${h.collaboration.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details><div class="action-buttons"><button data-collaboration>Download shared research brief ↓</button><button data-next-view="${research?'therapeutic':'researcher'}">${research?'Open MEDR5 therapeutic opportunities':'Explore the mechanism and evidence'} →</button></div><p class="muted small">${esc(h.collaboration.limitation)} This is a proposed collaboration, not a patient experiment.</p></section>
 <section class="card acceleration"><p class="eyebrow">10X ACCELERATION · A TESTABLE PRODUCT HYPOTHESIS</p><h3>The milestone: a defensible experimental-priority decision</h3><div class="acceleration-grid"><div><h4>Current manual path</h4><ol>${h.acceleration.current.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><div><h4>MEDR5 Atlas path</h4><ol>${h.acceleration.atlas.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div></div><p class="muted small"><b>No measured 10x claim.</b> ${esc(h.acceleration.assumption)}</p><details><summary>How to test the acceleration claim ⌄</summary><p>${esc(h.acceleration.measurement_plan)}</p></details></section>`;
}
async function exportCollaboration(){return previewBrief('collaboration');}
function priorPanel(b){
 const r=b.benchmark.relation_only,s=b.benchmark.source_disjoint;
 return `<section class="card prior-panel"><p class="eyebrow">SEPARATE DIMENSIONS · EVERY CURE-INSPIRED</p><h3>Disease-specific prior & connectivity</h3><p class="muted small">Direct-pair evidence helps frame the question; MEDR5 tests causal direction. No probability or combined AI score.</p>${b.comparison.map((c,i)=>`<div class="prior-row"><strong>${esc(c.name)}</strong><span>Evidence prior: ${c.repurposing_prior.score==null?'Unknown':c.repurposing_prior.score.toFixed(2)}</span><span>Local disease links: ${c.frequent_flyer.local_disease_degree}</span><span>Connectivity-adjusted priority: ${c.frequent_flyer.adjusted_priority==null?'Withheld':c.frequent_flyer.adjusted_priority.toFixed(2)}${c.eligible?'':' · not eligible'}</span><button data-prior="${i}">Inspect prior & normalisation ↗</button></div>`).join('')}<details><summary>Small withheld-link benchmark · limits visible ⌄</summary><p>Four cited positives: three preclinical mechanism observations and one clinical symptom RCT, not four established repurposing successes. Candidate pool: four interventions, including research comparators.</p><p>Relation-only ablation: Hit@1 ${pct(r.hit_at_1)}, Hit@3 ${pct(r.hit_at_3)}, MRR ${r.mrr.toFixed(3)}; ${r.abstentions}/${r.n} abstentions. It retains source-derived mechanism features and is a leakage-prone diagnostic.</p><p>Source-disjoint ablation: Hit@1 ${pct(s.hit_at_1)}; ${s.abstentions}/${s.n} abstentions. This pilot cannot recover relationships when their only mechanistic evidence is removed. No clinical generalisation is established.</p><p>Clinical-only fold: ${r.strata.clinical_symptom_evidence.abstentions}/1 abstention; symptom benefit is not causal restoration. Preclinical-only Hit@1: ${pct(r.strata.preclinical_mechanism.hit_at_1)}.</p><p class="muted small">Broadly connected drugs get no reward for disease count: positive priority is divided by √(max(1, cited disease links)). Degree is local and incomplete. Off-signature target breadth already carries MEDR5 spillover penalties.</p></details></section>`;
}
async function previewBrief(kind){
 const endpoint='/api/brief?id='+encodeURIComponent(state.bundle.disease.id)+'&type='+kind;
 try{const doc=await get(endpoint);showDetail(kind==='collaboration'?'Shared research brief':'Cited evidence brief',`<a class="button-link" href="${endpoint}&download=1" download="${esc(doc.filename)}">Save this brief (.txt) ↓</a><p class="muted small">Review the text below. If the embedded browser does not save files, open the demo in your usual browser.</p><pre class="brief-preview">${esc(doc.text)}</pre>`);}catch(e){showDetail('Brief unavailable',`<p>${esc(e.message)}</p>`);}
}
function showDetail(title,html){document.querySelector('#detail-title').textContent=title;document.querySelector('#detail-body').innerHTML=html;document.querySelector('#detail-dialog').showModal();}
function bind(){
 const b=state.bundle,p=b.ranking.ranked[0];
 document.querySelectorAll('[data-programme-source]').forEach(el=>el.onclick=()=>showDetail('NIH research programme — aims, not clinical proof',sourceRows(b.research_programmes[Number(el.dataset.programmeSource)].provenance)));
 document.querySelector('[data-action-evidence]').onclick=()=>showDetail('Proposed experiment: evidence and gaps',`<p>${esc(b.experiment.falsifier)}</p>${sourceRows(b.experiment.sources)}`);
 document.querySelector('[data-closing-atlas]').onclick=()=>{state.surface='atlas';render();};
 document.querySelectorAll('[data-surface]').forEach(el=>el.onclick=()=>{state.surface=el.dataset.surface;render();});
 document.querySelectorAll('[data-prior]').forEach(el=>el.onclick=()=>{const c=b.comparison[Number(el.dataset.prior)];showDetail('Evidence prior ≠ mechanistic fit',`<p>${esc(c.repurposing_prior.explanation)}</p>${sourceRows(c.repurposing_prior.sources)}<h3>Frequent-flyer correction</h3><p>${esc(c.frequent_flyer.explanation)}</p><p>${esc(c.frequent_flyer.scope)}. Recorded target breadth: ${c.frequent_flyer.recorded_target_breadth}. Factor: ${c.frequent_flyer.factor}.</p><p>Raw mechanistic fit: ${c.priority_score??'withheld'}; connectivity-adjusted priority: ${c.frequent_flyer.adjusted_priority??'withheld'}. Clinical safety is unchanged.</p>`);});
 document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;render();});
 document.querySelectorAll('[data-next-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.nextView==='therapeutic'?'researcher':el.dataset.nextView;state.surface=el.dataset.nextView==='therapeutic'?'therapeutic':'connections';render();document.querySelector('.view-tabs').scrollIntoView({behavior:'smooth',block:'start'});});
 document.querySelectorAll('[data-hero-sources]').forEach(el=>el.onclick=()=>{const hero=b.hero_journey;const k=el.dataset.heroSources;const refs=k==='cluster'?hero.neighbor.source_ids:k==='asset'?hero.asset.source_ids:k==='counter'?hero.counterexample.source_ids:hero.collaboration.source_ids;const rows=refs.map(id=>b.graph.nodes.flatMap(n=>n.provenance).find(s=>s.id===id));showDetail(k==='counter'?'Counterexample: direction is not interchangeable':'Connection and provenance',sourceRows(rows));});
 document.querySelectorAll('[data-collaboration]').forEach(el=>el.addEventListener('click',exportCollaboration));
 document.querySelectorAll('[data-biology]').forEach(el=>el.onclick=()=>showDetail('Causal direction & evidence',`<p>${esc(b.disease.mechanism)}</p>${sourceRows(b.sources.filter(s=>b.disease.source_ids.includes(s.id)))}`));
 document.querySelectorAll('[data-metric]').forEach(el=>el.onclick=()=>{
  const k=el.dataset.metric;let desc,rows=[];
  if(k==='priority'){desc=p.explanation;rows=p.evidence.sources;}
  if(k==='coverage'){desc='Coverage = sum of weights for sourced, favourably aligned axes / all curated signature weights. Each pilot molecular axis has weight 1. The single UBE3A axis is a narrow model, not a whole-disease map. No potency or clinical rescue is implied.';rows=p.evidence.sources;}
  if(k==='direction'){desc='Known disease loss + restoration aligns; gain + inhibition aligns. Opposite effects score −0.85 and block eligibility. Unknown or variant-dependent direction blocks ranking. Topotecan indirectly unsilences paternal UBE3A; it is not a direct UBE3A agonist.';rows=p.evidence.sources;}
  if(k==='spillover'){desc=p.spillover.explanation+' Listed: '+p.spillover.items.map(x=>x.target).join(', ');rows=b.studies.filter(s=>s.id==='king2013');}
  if(k==='evidence'){desc=p.evidence.explanation+` This candidate's uncertainty penalty is ${p.evidence.uncertainty_penalty}.`;rows=p.evidence.sources;}
  if(k==='risk'){desc=p.risk_burden.explanation;rows=[...new Map(p.source_ids.filter(id=>id==='topotecan-label').map(id=>[id,{...b.graph.nodes.find(n=>n.id==='topotecan').provenance.find(s=>s.id===id)}])).values()];}
  showDetail(k==='risk'?'Clinical safety evidence — separate from fit':'How this metric works',`<p>${esc(desc)}</p>${sourceRows(rows)}`);
 });
 document.querySelector('[data-show-sources]')?.addEventListener('click',()=>showDetail('Topotecan: supporting evidence',sourceRows(b.graph.nodes.find(n=>n.id==='topotecan').provenance)));
 document.querySelectorAll('[data-surrogate]').forEach(el=>el.onclick=()=>{const s=b.surrogates[Number(el.dataset.surrogate)];showDetail('Mechanistic comparison',`<p>${esc(s.explanation)}</p>${sourceRows(s.sources)}`);});
 document.querySelector('[data-experiment-sources]').onclick=()=>showDetail('Sources for a proposed experiment',`<p>This experiment is a hypothesis generated from the cited findings, not a completed study or a patient intervention.</p>${sourceRows(b.experiment.sources)}`);
 document.querySelectorAll('[data-audience]').forEach(el=>el.onclick=()=>{state.tab=el.dataset.audience;renderActions();});
 document.querySelector('#export-brief').onclick=exportBrief;
 document.querySelector('#replay-ai').onclick=()=>runAI(false);document.querySelector('#live-ai').onclick=()=>runAI(true);document.querySelector('#openai-ai').onclick=()=>runAI(true,'openai');
}
function renderActions(){
 const b=state.bundle;document.querySelectorAll('[data-audience]').forEach(btn=>btn.setAttribute('aria-selected',btn.dataset.audience===state.tab));
 document.querySelector('#action-list').innerHTML=`<p class="audience-note">${state.tab==='patient'?'Resources to discuss with a treating clinician. Medicines shown elsewhere are research hypotheses, not treatment suggestions.':'A prioritisation workflow for research, with gaps and falsifiers visible.'}</p>`+b.next_steps[state.tab].map((a,i)=>`<article><span class="action-number">0${i+1}</span><div><h4>${esc(a.title)}</h4><p>${esc(a.text)}</p>${a.url?`<a href="${url(a.url)}" target="_blank" rel="noopener noreferrer">Open source resource ↗</a>`:''}</div></article>`).join('');
}
function renderGraph(){
 const b=state.bundle;const types=[...new Set(b.graph.nodes.map(n=>n.type))];
 document.querySelector('#graph-view').insertAdjacentHTML('beforebegin','<label class="relationship-picker"><span>Inspect a cited relationship</span><select id="relationship-select"><option value="">Choose a connection…</option></select></label>');
 document.querySelector('#relationship-select').onchange=e=>{if(e.target.value)inspectGraph(e.target.value);};
 document.querySelector('#graph-controls').innerHTML=types.map(t=>`<label><input type="checkbox" data-filter="${esc(t)}" ${state.filters.has(t)?'checked':''}><span>${esc(t==='Phenotype'?'Symptom':t)}</span></label>`).join('');
 document.querySelectorAll('[data-filter]').forEach(el=>el.onchange=()=>{if(el.checked)state.filters.add(el.dataset.filter);else state.filters.delete(el.dataset.filter);drawGraph();});
 document.querySelector('#zoom-in').onclick=()=>{state.zoom=Math.min(2,state.zoom+.25);drawGraph();};
 document.querySelector('#zoom-out').onclick=()=>{state.zoom=Math.max(.75,state.zoom-.25);drawGraph();};
 document.querySelector('#zoom-reset').onclick=()=>{state.zoom=1;drawGraph();};drawGraph();
}
function drawGraph(){
 const graph=state.bundle.graph,visible=graph.nodes.filter(n=>state.filters.has(n.type)),positions=new Map();
 const lane={Disease:0,Phenotype:0,Gene:1,Variant:1,Pathway:1,Drug:2,Intervention:2,Experiment:2,Asset:2,Study:3,Trial:3,'Patient Group':3,'Research Team':3};
 const counts=[0,0,0,0];for(const n of visible){const l=lane[n.type]??1;positions.set(n.id,{x:110+l*245,y:55+counts[l]++*66});}
 const height=Math.max(460,Math.max(...counts)*66+55);
 const edges=graph.edges.filter(e=>positions.has(e.source)&&positions.has(e.target));
 document.querySelector('#relationship-select').innerHTML='<option value="">Choose a connection…</option>'+edges.map(e=>`<option value="${e.id}" ${state.selected===e.id?'selected':''}>${esc(graph.nodes.find(n=>n.id===e.source).label)} → ${esc(e.type.replaceAll('_',' ').toLowerCase())} → ${esc(graph.nodes.find(n=>n.id===e.target).label)}</option>`).join('');
 const svg=`<svg role="img" aria-label="Evidence-backed knowledge graph for ${esc(state.bundle.disease.name)}" viewBox="0 0 ${1000/state.zoom} ${height/state.zoom}"><title>Knowledge graph: selectable sourced nodes and edges</title>${edges.map(e=>{const a=positions.get(e.source),b=positions.get(e.target);return `<g data-edge="${e.id}"><title>${esc(e.type)}</title><line class="edge-hit" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><line class="graph-edge ${state.selected===e.id?'selected':''}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/></g>`;}).join('')}${edges.map(e=>{const a=positions.get(e.source),b=positions.get(e.target);return `<circle class="edge-point-hit" role="button" tabindex="0" data-edge="${e.id}" aria-label="Inspect ${esc(e.type)}" cx="${(a.x+b.x)/2}" cy="${(a.y+b.y)/2}" r="7"><title>${esc(e.type)}</title></circle>`;}).join('')}${visible.map(n=>{const p=positions.get(n.id);let label=n.label.length>26?n.label.slice(0,24)+'…':n.label;return `<g class="graph-node type-${n.type.replaceAll(' ','')} ${state.selected===n.id?'selected':''}" transform="translate(${p.x},${p.y})" data-node="${esc(n.id)}" role="button" tabindex="0" aria-label="Inspect ${esc(n.type)} ${esc(n.label)}"><title>${esc(n.label)}</title><rect x="-102" y="-22" width="204" height="44" rx="9"/><text x="-90" y="-3" class="node-type">${esc(n.type)}</text><text x="-90" y="13">${esc(label)}</text></g>`;}).join('')}</svg>`;
 document.querySelector('#graph-view').innerHTML=visible.length?svg:'<p class="empty-graph">Select at least one node type to view evidence.</p>';
 document.querySelectorAll('[data-node],[data-edge]').forEach(el=>{const select=()=>inspectGraph(el.dataset.node||el.dataset.edge);el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};});
}
function inspectGraph(id){
 const g=state.bundle.graph,item=g.nodes.find(n=>n.id===id)||g.edges.find(e=>e.id===id);if(!item)return;
 state.selected=id;const inspector=document.querySelector('#graph-inspector');
 inspector.innerHTML=`<span class="badge">${esc(item.classification)} · ${esc(item.type)}</span><h3>${esc(item.label||item.type.replaceAll('_',' '))}</h3><p>${esc(item.description)}</p><p class="small">${esc(item.confidence)} · ${esc(item.observed_or_inferred)}</p>${item.ontology_identifiers?.length?`<p><b>Stable identifiers:</b> ${item.ontology_identifiers.map(x=>esc(x.identifier)+' · '+esc(x.mapping_scope)).join('<br>')}</p>`:''}<p class="small"><b>Contradictions / limitations:</b> ${esc(item.contradictory_evidence)}</p>${sourceRows(item.provenance)}`;drawGraph();
}
async function runAI(live,provider='local'){
 const div=document.querySelector('#ai-result');div.textContent=live?`Requesting a source-bound ${provider==='openai'?'OpenAI':'local model'} draft…`:'Loading saved draft…';
 try{const response=await fetch('/api/ai/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_id:'huang2012',disease_id:state.bundle.disease.id,live,provider})});const data=await response.json();if(!response.ok)throw Error(data.error);
 div.innerHTML=`<article class="ai-result"><b>${esc(data.mode)}</b><p>${esc(data.notice||data.message||'')}</p>${data.relationships?.map(r=>`<p><code>${esc(r.subject)} → ${esc(r.predicate)} → ${esc(r.object)}</code></p><blockquote>${esc(r.source_span)}</blockquote><span class="badge amber">DRAFT · SEMANTIC REVIEW REQUIRED</span>`).join('')||''}${data.source?sourceLink(data.source):''}</article>`;
 }catch(e){div.textContent=e.message;}
}
async function exportBrief(){return previewBrief('evidence');}
shell();
loadDisease('angelman');
